spring.application.name=request_processor
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/request_processor
spring.datasource.username=postgres
spring.datasource.password=12345
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Outbox settings
outbox.batch-size=50
outbox.delay-ms=1000

# Kafka
kafka.bootstrap-servers=localhost:9092


# Optional: Spring Kafka properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true